# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QFont
from PyQt5.QtWidgets import QFileDialog, QDesktopWidget, QWidget, QApplication

from PyQt5.QtWidgets import QTableWidget, QTableWidgetItem

from thread import Worker
import demo_rc
import methods
import os

from openpyxl import load_workbook


class Ui_MainWindow(QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2000, 1000)
        MainWindow.showMaximized()

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1500, 900))
        self.centralwidget.setStyleSheet("#centralwidget{border-image: url(:/logo/背景.jpg);}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(700, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.groupBox_3)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.comboBox = QtWidgets.QComboBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_4.addWidget(self.comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.radioButton = QtWidgets.QRadioButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton.sizePolicy().hasHeightForWidth())
        self.radioButton.setSizePolicy(sizePolicy)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_4.addWidget(self.radioButton)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_4.setStretch(2, 1)
        self.verticalLayout_4.setStretch(3, 1)
        self.verticalLayout_4.setStretch(4, 1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.tab_3)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout_7.addWidget(self.comboBox_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_2.sizePolicy().hasHeightForWidth())
        self.radioButton_2.setSizePolicy(sizePolicy)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_7.addWidget(self.radioButton_2)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 1)
        self.verticalLayout_7.setStretch(2, 1)
        self.verticalLayout_7.setStretch(3, 1)
        self.verticalLayout_7.setStretch(4, 1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_6.addWidget(self.pushButton_2)
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.tab_5)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_9.addWidget(self.label_11)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem4)
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        self.comboBox_3.setObjectName("comboBox_3")
        self.verticalLayout_9.addWidget(self.comboBox_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem5)
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_3.sizePolicy().hasHeightForWidth())
        self.radioButton_3.setSizePolicy(sizePolicy)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_9.addWidget(self.radioButton_3)
        self.verticalLayout_9.setStretch(0, 1)
        self.verticalLayout_9.setStretch(1, 1)
        self.verticalLayout_9.setStretch(2, 1)
        self.verticalLayout_9.setStretch(3, 1)
        self.verticalLayout_9.setStretch(4, 1)
        self.horizontalLayout_6.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_8.addWidget(self.pushButton_3)
        self.label_10 = QtWidgets.QLabel(self.tab_5)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_8.addWidget(self.label_10)
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_13 = QtWidgets.QLabel(self.tab_6)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_11.addWidget(self.label_13)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem6)
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_4.sizePolicy().hasHeightForWidth())
        self.comboBox_4.setSizePolicy(sizePolicy)
        self.comboBox_4.setObjectName("comboBox_4")
        self.verticalLayout_11.addWidget(self.comboBox_4)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem7)
        self.radioButton_4 = QtWidgets.QRadioButton(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_4.sizePolicy().hasHeightForWidth())
        self.radioButton_4.setSizePolicy(sizePolicy)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_11.addWidget(self.radioButton_4)
        self.verticalLayout_11.setStretch(0, 1)
        self.verticalLayout_11.setStretch(1, 1)
        self.verticalLayout_11.setStretch(2, 1)
        self.verticalLayout_11.setStretch(3, 1)
        self.verticalLayout_11.setStretch(4, 1)
        self.horizontalLayout_7.addLayout(self.verticalLayout_11)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_10.addWidget(self.pushButton_4)
        self.label_12 = QtWidgets.QLabel(self.tab_6)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_10.addWidget(self.label_12)
        self.horizontalLayout_7.addLayout(self.verticalLayout_10)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tab_7)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_15 = QtWidgets.QLabel(self.tab_7)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_13.addWidget(self.label_15)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem8)
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_5.sizePolicy().hasHeightForWidth())
        self.comboBox_5.setSizePolicy(sizePolicy)
        self.comboBox_5.setObjectName("comboBox_5")
        self.verticalLayout_13.addWidget(self.comboBox_5)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem9)
        self.radioButton_5 = QtWidgets.QRadioButton(self.tab_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_5.sizePolicy().hasHeightForWidth())
        self.radioButton_5.setSizePolicy(sizePolicy)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_13.addWidget(self.radioButton_5)
        self.verticalLayout_13.setStretch(0, 1)
        self.verticalLayout_13.setStretch(1, 1)
        self.verticalLayout_13.setStretch(2, 1)
        self.verticalLayout_13.setStretch(3, 1)
        self.verticalLayout_13.setStretch(4, 1)
        self.horizontalLayout_8.addLayout(self.verticalLayout_13)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_12.addWidget(self.pushButton_5)
        self.label_14 = QtWidgets.QLabel(self.tab_7)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_12.addWidget(self.label_14)
        self.horizontalLayout_8.addLayout(self.verticalLayout_12)
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.tab_8)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_17 = QtWidgets.QLabel(self.tab_8)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_15.addWidget(self.label_17)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem10)
        self.comboBox_6 = QtWidgets.QComboBox(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_6.sizePolicy().hasHeightForWidth())
        self.comboBox_6.setSizePolicy(sizePolicy)
        self.comboBox_6.setObjectName("comboBox_6")
        self.verticalLayout_15.addWidget(self.comboBox_6)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem11)
        self.radioButton_6 = QtWidgets.QRadioButton(self.tab_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_6.sizePolicy().hasHeightForWidth())
        self.radioButton_6.setSizePolicy(sizePolicy)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_15.addWidget(self.radioButton_6)
        self.verticalLayout_15.setStretch(0, 1)
        self.verticalLayout_15.setStretch(1, 1)
        self.verticalLayout_15.setStretch(2, 1)
        self.verticalLayout_15.setStretch(3, 1)
        self.verticalLayout_15.setStretch(4, 1)
        self.horizontalLayout_9.addLayout(self.verticalLayout_15)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_14.addWidget(self.pushButton_6)
        self.label_16 = QtWidgets.QLabel(self.tab_8)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_14.addWidget(self.label_16)
        self.horizontalLayout_9.addLayout(self.verticalLayout_14)
        self.tabWidget_2.addTab(self.tab_8, "")
        self.horizontalLayout_3.addWidget(self.tabWidget_2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(260, 250))
        self.groupBox_2.setMaximumSize(QtCore.QSize(260, 250))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Image_Choose = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Image_Choose.sizePolicy().hasHeightForWidth())
        self.Image_Choose.setSizePolicy(sizePolicy)
        self.Image_Choose.setMinimumSize(QtCore.QSize(240, 80))
        self.Image_Choose.setMaximumSize(QtCore.QSize(240, 80))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        self.Image_Choose.setFont(font)
        self.Image_Choose.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Image_Choose.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.403273, y2:0.494318, stop:0 rgba(173, 173, 173, 255), stop:1 rgba(255, 255, 255, 255));")
        self.Image_Choose.setIconSize(QtCore.QSize(8, 3))
        self.Image_Choose.setObjectName("Image_Choose")
        self.verticalLayout_5.addWidget(self.Image_Choose)
        self.Start = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Start.sizePolicy().hasHeightForWidth())
        self.Start.setSizePolicy(sizePolicy)
        self.Start.setMinimumSize(QtCore.QSize(240, 80))
        self.Start.setMaximumSize(QtCore.QSize(240, 80))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        self.Start.setFont(font)
        self.Start.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Start.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0.403273, y2:0.494318, stop:0 rgba(173, 173, 173, 255), stop:1 rgba(255, 255, 255, 255));")
        self.Start.setIconSize(QtCore.QSize(8, 3))
        self.Start.setObjectName("Start")
        self.verticalLayout_5.addWidget(self.Start)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.horizontalLayout_3.setStretch(1, 3)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem12)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(700, 300))
        self.groupBox_4.setMaximumSize(QtCore.QSize(700, 1500))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.table = QtWidgets.QTableWidget(self.groupBox_4)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.verticalLayout.addWidget(self.table)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.verticalLayout_2.setStretch(0, 4)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 7)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem13)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setMinimumSize(QtCore.QSize(100, 100))
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.inputimg = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputimg.sizePolicy().hasHeightForWidth())
        self.inputimg.setSizePolicy(sizePolicy)
        self.inputimg.setMinimumSize(QtCore.QSize(10, 10))
        self.inputimg.setMaximumSize(QtCore.QSize(20000, 20000))
        self.inputimg.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.inputimg.setFrameShape(QtWidgets.QFrame.Box)
        self.inputimg.setObjectName("inputimg")
        self.gridLayout_2.addWidget(self.inputimg, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setMinimumSize(QtCore.QSize(100, 100))
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.outputimg = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputimg.sizePolicy().hasHeightForWidth())
        self.outputimg.setSizePolicy(sizePolicy)
        self.outputimg.setMinimumSize(QtCore.QSize(10, 10))
        self.outputimg.setMaximumSize(QtCore.QSize(20000, 20000))
        self.outputimg.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.outputimg.setFrameShape(QtWidgets.QFrame.Box)
        self.outputimg.setObjectName("outputimg")
        self.gridLayout_3.addWidget(self.outputimg, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 8)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.title = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        self.title.setMinimumSize(QtCore.QSize(10, 150))
        self.title.setMaximumSize(QtCore.QSize(16777215, 150))
        self.title.setStyleSheet("")
        self.title.setTextFormat(QtCore.Qt.AutoText)
        self.title.setObjectName("title")
        self.horizontalLayout.addWidget(self.title)
        self.logo = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMinimumSize(QtCore.QSize(150, 150))
        self.logo.setMaximumSize(QtCore.QSize(150, 150))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/logo/校徽.png"))
        self.logo.setScaledContents(True)
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.horizontalLayout.addWidget(self.logo)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1385, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # 重设置各功能区边框以及字体
        # self.groupBox.setStyleSheet("QGroupBox { color: white; border: 2px solid white;}")
        self.groupBox_2.setStyleSheet("QGroupBox { color: white; border: 2px solid white;}")
        self.groupBox_3.setStyleSheet("QGroupBox { color: white; border: 2px solid white;}")
        self.groupBox_4.setStyleSheet("QGroupBox { color: white; border: 2px solid white;}")
        # 绑定按键功能
        self.Image_Choose.clicked.connect(self.ImageChoose)
        self.Start.clicked.connect(self.QtStart)

        # 重写resize功能
        MainWindow.resizeEvent = self.ResizeEvent

        # 初始化各个功能中的下拉框
        self.comboBox.mousePressEvent = lambda event, idx=1: self.onComboClicked(idx, event)
        self.comboBox_2.mousePressEvent = lambda event, idx=2: self.onComboClicked(idx, event)
        self.comboBox_3.mousePressEvent = lambda event, idx=3: self.onComboClicked(idx, event)
        self.comboBox_4.mousePressEvent = lambda event, idx=4: self.onComboClicked(idx, event)
        self.comboBox_5.mousePressEvent = lambda event, idx=5: self.onComboClicked(idx, event)
        self.comboBox_6.mousePressEvent = lambda event, idx=6: self.onComboClicked(idx, event)
        self.comboBox_already_filled = self.comboBox_2_already_filled = self.comboBox_3_already_filled = self.comboBox_4_already_filled = self.comboBox_5_already_filled = self.comboBox_6_already_filled = False
        # self.comboBox_2.currentTextChanged.connect(self.update_functions)

        # self.Ship_or_Aircraft.mousePressEvent = self.onComboClicked
        # self.Ship_or_Aircraft_already_filled = False
        # self.Ship_or_Aircraft.currentTextChanged.connect(self.update_functions)

        # 定义各个目录
        self.imgpath = ""
        self.savepath = ""
        self.outputpath = ""
        self.current_directory = os.getcwd()



    def onComboClicked(self, index, event):
        font = QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setPointSize(9)
        # 机场检测
        if index == 1:
            QtWidgets.QComboBox.showPopup(self.comboBox)
            if not self.comboBox_already_filled:
                self.comboBox.setFont(font)
                self.comboBox.addItems(['机场检测方法1'])
                self.comboBox_already_filled = True
        # 飞机检测
        if index == 2:
            QtWidgets.QComboBox.showPopup(self.comboBox_2)
            if not self.comboBox_2_already_filled:
                self.comboBox_2.setFont(font)
                self.comboBox_2.addItems(['飞机检测算法1'])
                self.comboBox_2_already_filled = True
        # 飞机识别
        if index == 3:
            QtWidgets.QComboBox.showPopup(self.comboBox_3)
            if not self.comboBox_3_already_filled:
                self.comboBox_3.setFont(font)
                self.comboBox_3.addItems(['飞机识别算法1'])
                self.comboBox_3_already_filled = True
        # 海陆分割
        if index == 4:
            QtWidgets.QComboBox.showPopup(self.comboBox_4)
            if not self.comboBox_4_already_filled:
                self.comboBox_4.setFont(font)
                self.comboBox_4.addItems(['海陆分割算法1'])
                self.comboBox_4_already_filled = True
        # 舰船检测
        if index == 5:
            QtWidgets.QComboBox.showPopup(self.comboBox_5)
            if not self.comboBox_5_already_filled:
                self.comboBox_5.setFont(font)
                self.comboBox_5.addItems(['水平框检测', '旋转框检测'])
                self.comboBox_5_already_filled = True
        # 舰船识别
        if index == 6:
            QtWidgets.QComboBox.showPopup(self.comboBox_6)
            if not self.comboBox_6_already_filled:
                self.comboBox_6.setFont(font)
                self.comboBox_6.addItems(['舰船识别算法1'])
                self.comboBox_6_already_filled = True

    # 图像选择
    def ImageChoose(self):
        if self.imgpath != "":
            self.imgpath = ""
            self.savepath = ""
            self.outputpath = ""
            self.inputimg.setText("<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">输入图片</span></p></body></html>")
            self.outputimg.setText("<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">输出图片</span></p></body></html>")
        file_path, _ = QFileDialog.getOpenFileName(self, "选择文件", "","All Files(*)",None,QFileDialog.DontUseNativeDialog)
        if file_path == "":
            pass
        else:
            print(file_path)
            self.imgpath = file_path
            self.showinputimg()
        print("Image_Choose")

    # 传递到调用函数，开始按键
    def QtStart(self):
        try:
            function = self.tabWidget_2.currentIndex()
            if function == 0 and self.comboBox.currentText() != '':
                self.functions("Airport_Detection", self.comboBox.currentText())
            elif function == 1 and self.comboBox_2.currentText() != '':
                self.functions("Aircraft_Detection", self.comboBox_2.currentText())
            elif function == 2 and self.comboBox_3.currentText() != '':
                self.functions("Aircraft_Identification", self.comboBox_3.currentText())
            elif function == 3 and self.comboBox_4.currentText() != '':
                self.functions("Sea_or_Land", self.comboBox_4.currentText())
            elif function == 4 and self.comboBox_5.currentText() != '':
                self.functions("Ship_Detection", self.comboBox_5.currentText())
            elif function == 5 and self.comboBox_6.currentText() != '':
                self.functions("Ship_Identification", self.comboBox_6.currentText())
        except AttributeError:
            methods.message_functionchoose()

    # 设定保存目录
    def Save_path(self):
        self.outputpath = ""
        save_path = QFileDialog.getExistingDirectory(self, "选取文件夹", "C:/", QFileDialog.ShowDirsOnly)
        if save_path == ".":
            pass
        else:
            print(save_path)
            self.savepath = save_path
        print("Save_path")

    # 实现调用函数，调用线程
    def functions(self, function, method):
        imgpath = self.imgpath
        if self.savepath == "":
            savepath = self.current_directory + "/output/" + function + "/"
        else:
            savepath = self.savepath + "/" + function + "/"
        self.outputpath = savepath
        if methods.message_button(imgpath, savepath):
            self.thread = Worker(imgpath, savepath, function, method)
            self.thread.finished.connect(self.Finished)
            self.thread.start()

    def Finished(self):
        # 线程完成后执行的操作
        self.showoutputimg()

        self.read_xlsx()


    def ResizeEvent(self, event):
        if self.imgpath:
            self.showinputimg()
            self.showoutputimg()
        super(Ui_MainWindow, self).resizeEvent(event)

    def showinputimg(self):
        if self.imgpath:
            input_img = QtGui.QPixmap(self.imgpath).scaled(self.inputimg.width(), self.inputimg.height())
            self.inputimg.setPixmap(input_img)
            self.inputimg.setScaledContents(True)

    def showoutputimg(self):
        if self.outputpath:
            output_img_path = os.path.join(self.outputpath, "output.png")
            output_img = QtGui.QPixmap(output_img_path).scaled(self.outputimg.width(), self.outputimg.height())
            self.outputimg.setPixmap(output_img)
            self.outputimg.setScaledContents(True)

    def read_output_txt(self):
        self.out_info.clear()
        txt_path = os.path.join(self.outputpath, "output.txt")
        if os.path.exists(txt_path):
            with open(txt_path, 'r') as f:
                content = f.read()
                self.out_info.setText(content)

    def read_xlsx(self):
        self.table.clear()
        xlsx_path = os.path.join(self.outputpath, "output.xlsx")
        if os.path.exists(xlsx_path):
            book = load_workbook(filename=xlsx_path)  # 使用正确的路径
            sheet = book.active
            nrows = sheet.max_row  # 取最大行数
            ncols = sheet.max_column  # 取最大列数
            if ncols > 26:
                print(f"Columns: {ncols} > 26! Reducing to 26.")
                ncols = 26
            self.table.setRowCount(nrows)  # 设置行数
            self.table.setColumnCount(ncols)  # 设置列数
            headers = tuple("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
            self.table.setHorizontalHeaderLabels(headers[:ncols])  # 限制表头只到26个字母

            self.table.setUpdatesEnabled(False)  # 禁用更新以提高性能

            # 遍历Excel数据并插入到表格控件中
            for row, row_data in enumerate(sheet.iter_rows(max_row=nrows, max_col=ncols)):
                for col, cell in enumerate(row_data):
                    item = QTableWidgetItem(self.format_cell(cell))
                    self.table.setItem(row, col, item)
            self.table.setColumnWidth(1, 300)
            self.table.setColumnWidth(2, 200)
            self.table.setUpdatesEnabled(True)

    def format_cell(self, cell):
        """ 根据单元格类型格式化单元格数据 """
        if cell.value is None:
            return ''
        elif cell.data_type == 's':  # string
            return str(cell.value)
        elif cell.data_type == 'n':  # number
            if isinstance(cell.value, int):
                return str(cell.value)
            else:  # float
                return f"{cell.value:.4f}"
        elif cell.data_type == 'd':  # date
            return cell.value.strftime('%Y-%m-%d')
        else:
            return str(cell.value)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tools_for_SAR"))
        self.groupBox_3.setTitle(_translate("MainWindow", "操作区"))
        self.label.setText(_translate("MainWindow", "选择检测方法"))
        self.radioButton.setText(_translate("MainWindow", "方法确认"))
        self.pushButton.setText(_translate("MainWindow", "选择保存位置"))
        self.label_7.setText(_translate("MainWindow", "保存路径"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "机场检测"))
        self.label_9.setText(_translate("MainWindow", "选择检测方法"))
        self.radioButton_2.setText(_translate("MainWindow", "方法确认"))
        self.pushButton_2.setText(_translate("MainWindow", "选择保存位置"))
        self.label_8.setText(_translate("MainWindow", "保存路径"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "飞机检测"))
        self.label_11.setText(_translate("MainWindow", "选择检测方法"))
        self.radioButton_3.setText(_translate("MainWindow", "方法确认"))
        self.pushButton_3.setText(_translate("MainWindow", "选择保存位置"))
        self.label_10.setText(_translate("MainWindow", "保存路径"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "飞机识别"))
        self.label_13.setText(_translate("MainWindow", "选择检测方法"))
        self.radioButton_4.setText(_translate("MainWindow", "方法确认"))
        self.pushButton_4.setText(_translate("MainWindow", "选择保存位置"))
        self.label_12.setText(_translate("MainWindow", "保存路径"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "海陆分割"))
        self.label_15.setText(_translate("MainWindow", "选择检测方法"))
        self.radioButton_5.setText(_translate("MainWindow", "方法确认"))
        self.pushButton_5.setText(_translate("MainWindow", "选择保存位置"))
        self.label_14.setText(_translate("MainWindow", "保存路径"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "舰船检测"))
        self.label_17.setText(_translate("MainWindow", "选择检测方法"))
        self.radioButton_6.setText(_translate("MainWindow", "方法确认"))
        self.pushButton_6.setText(_translate("MainWindow", "选择保存位置"))
        self.label_16.setText(_translate("MainWindow", "保存路径"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "舰船识别"))
        self.groupBox_2.setTitle(_translate("MainWindow", "执行按键"))
        self.Image_Choose.setText(_translate("MainWindow", "选择图片"))
        self.Start.setText(_translate("MainWindow", "开始"))
        self.groupBox_4.setTitle(_translate("MainWindow", "输出信息"))
        self.inputimg.setText(_translate("MainWindow",
                                         "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">输入图片</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "输入图片"))
        self.outputimg.setText(_translate("MainWindow",
                                          "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">输出图片</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "输出图片"))
        self.title.setText(_translate("MainWindow",
                                      "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600; color:#ffffff;\">卫星SAR图像目标检测识别软件</span></p></body></html>"))


